export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum AccountActivity {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  CHANGE_PASSWORD = 'CHANGE PASSWORD',
  REACTIVATE = 'REACTIVATE',
  UPLOAD_FILE = 'UPLOAD FILE',
  MODIFY_ACADEMIC = 'MODIFY ACADEMICS',
  MODIFY_EXPERIENCE = 'MODIFY EXPERIENCES',
  MODIFY_CERTIFICATE = 'MODIFY CERTIFICATES',
  MODIFY_ACHIEVEMENT = 'MODIFY ACHIEVEMENTS',
  MODIFY_SCHEDULE = 'MODIFY SCHEDULES',
  MODIFY_TREATMENT = 'MODIFY TREATMENTS',
}

export enum AccountType {
  ADMIN = 'ADMIN',
  USER = 'USER',
  DOCTOR = 'DOCTOR',
}

export enum JwtName {
  ADMIN = 'adminJWT',
  USER = 'userJWT',
  DOCTOR = 'doctorJWT',
}
